//
// Created by Arya Rakha on 6/4/2023.
//

#ifndef CMAKESFMLPROJECT_IFIXEDUPDATABLESYSTEM_H
#define CMAKESFMLPROJECT_IFIXEDUPDATABLESYSTEM_H


class IFixedUpdatableSystem {

};


#endif //CMAKESFMLPROJECT_IFIXEDUPDATABLESYSTEM_H
